script: bash ./bin/deploy.sh
env:
  global:
  - GH_REF: github.com/clintonhalpin/react-image-panel.git
  - secure: SoCWYliZ/JbT0YgHjNg6KsUCodDx/ibWesTw+f+AMMCEgRSoN5XH4W8uGOwpMHAVI/YaYqRjdmSTSjZMCRQYBjlUF6mQhMusJozM6mfNoomV/jXpygG2Mkfx2+189LVBAdImku6dlzTte2gYesjh+lRI4tKCJFFRS2Wpi12gr6Jyc6cms0CHwRmv7xk81R/NU328Q1oAovkDYdWz//2Biy5giiVEUn9QVk5UvwZJb54jhBrhl5DW6qPrsfNWgaP0SynvdO7hrgdYVYNvsNX8micLWB9iuJREDNQttNsauXpiVYpG/QMSSZcCH7GjQrTXDxlKvUjeJifhwHD+p3arCIFFa1GkXf04wkPgia5vtbam0CQPQ5NwaiexGgIQOBpgOOmfMm2tavFj73nB7zwMBS+QMlP6hdQ8MbHXv4VFPxe2uFeXwkaiJNgkdleVchLS5evSDYa6IATaWnXbV2v+nzklmPqQcxvzYtUe2jJW9ZY2PXNwY1+iYARMeSDSdb9rguxywoC+h78HHhCrHkJygzPGMBCVpyeHJiOOpXR0OVOGDA3/MWybQjBYkc+jT3hQ+x5mEG8eQYW/eExcRj+oMoPeIgr0KT4NULK/AbZfAMkfxMrYyMDgvs97e9exJG5Ojp10dtW7d/hpHt/Lj6BVJhQzy0u25HZSB8+1DFXcyNg=
language: node_js
node_js:
- '4.0'
cache: 
  directories:
    - node_modules
branches:
  only:
    - gh-pages 
